from fastapi import APIRouter, HTTPException
from fastapi.responses import StreamingResponse
from pydantic import BaseModel
import markdown2
from xhtml2pdf import pisa
from io import BytesIO

router = APIRouter()

class ExportRequest(BaseModel):
    notes: str

@router.post("/export/pdf")
async def export_pdf(request: ExportRequest):
    try:
        # 1. Convert Markdown to HTML
        html_content = markdown2.markdown(request.notes)

        # 2. Add styling
        styled_html = f"""
        <html>
        <head>
            <style>
                body {{
                    font-family: Helvetica, sans-serif;
                    font-size: 12pt;
                    line-height: 1.5;
                    color: #333;
                }}
                h1 {{ color: #2563eb; font-size: 24pt; margin-bottom: 20px; border-bottom: 2px solid #2563eb; padding-bottom: 10px; }}
                h2 {{ color: #1e40af; font-size: 18pt; margin-top: 20px; margin-bottom: 10px; }}
                h3 {{ color: #1e3a8a; font-size: 14pt; margin-top: 15px; margin-bottom: 8px; }}
                p {{ margin-bottom: 10px; text-align: justify; }}
                ul {{ margin-bottom: 10px; }}
                li {{ margin-bottom: 5px; }}
                code {{ background-color: #f3f4f6; padding: 2px 4px; border-radius: 4px; font-family: Courier, monospace; }}
                pre {{ background-color: #f3f4f6; padding: 10px; border-radius: 8px; overflow-x: auto; }}
            </style>
        </head>
        <body>
            {html_content}
            <div style="margin-top: 50px; text-align: center; font-size: 10pt; color: #666;">
                Generated by NotesBuddy AI
            </div>
        </body>
        </html>
        """

        # 3. Convert HTML to PDF
        pdf_buffer = BytesIO()
        pisa_status = pisa.CreatePDF(styled_html, dest=pdf_buffer)

        if pisa_status.err:
            raise HTTPException(status_code=500, detail="PDF generation failed")

        pdf_buffer.seek(0)

        # 4. Return PDF
        return StreamingResponse(
            pdf_buffer,
            media_type="application/pdf",
            headers={"Content-Disposition": "attachment; filename=notes.pdf"}
        )

    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))
