"""Add transcript column

Revision ID: 3f86a13c48f1
Revises: 241f0c5c6ecb
Create Date: 2025-12-24 15:10:24.133261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f86a13c48f1'
down_revision: Union[str, Sequence[str], None] = '241f0c5c6ecb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('transcript', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notes', 'transcript')
    # ### end Alembic commands ###
