"""Add language and 
style to notes

Revision ID: f929ac63b422
Revises: c587659b58b4
Create Date: 2025-12-04 17:26:23.892126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f929ac63b422'
down_revision: Union[str, Sequence[str], None] = 'c587659b58b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('language', sa.String(), nullable=True))
    op.add_column('notes', sa.Column('style', sa.String(), nullable=True))
    op.drop_index(op.f('ix_notes_video_id'), table_name='notes')
    op.create_index(op.f('ix_notes_video_id'), 'notes', ['video_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notes_video_id'), table_name='notes')
    op.create_index(op.f('ix_notes_video_id'), 'notes', ['video_id'], unique=True)
    op.drop_column('notes', 'style')
    op.drop_column('notes', 'language')
    # ### end Alembic commands ###
